language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3

branches:
  only:
    - master

services:
  - docker

before_install:
  - gem update --system
  - gem install bundler
  - gem install rubocop

script:
  - rake lint
  - rake build

jobs:
  include:
    - stage: docker
      name: "Building sysmoon in a container"
      script:
        - |
          docker build \
          --file dockerfiles/centos.dockerfile \
          --tag sysmoon:latest \
          .
