language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3

branches:
  only:
    - master

services:
  - docker

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle exec rake lint
  - bundle exec rake test
  - bundle exec rake build

jobs:
  include:
    - stage: rpm
      name: "Building RPM package"
      script:
        - bundle exec rake build-rpm
    - stage: docker
      name: "Building evesync in a CentOS container"
      script:
        - |
          docker build \
          --file dockerfiles/centos.dockerfile \
          --tag evesync-rhel:latest \
          .
    - stage: docker
      name: "Building evesync in a Debian container"
      script:
        - |
          docker build \
          --file dockerfiles/debian.dockerfile \
          --tag evesync-deb:latest \
          .
    - stage: docker
      name: "Building evesync in a ArchLinux container"
      script:
        - |
          docker build \
          --file dockerfiles/archlinux.dockerfile \
          --tag evesync-arch:latest \
          .
