language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3

branches:
  only:
    - master

services:
  - docker

before_install:
  - gem update --system
  - gem install bundler
  - gem install rubocop

script:
  - rake lint
  - rake test
  - rake build

jobs:
  include:
    - stage: docker
      name: "Building sysmoon in a CentOS container"
      script:
        - |
          docker build \
          --file dockerfiles/centos.dockerfile \
          --tag sysmoon-rhel:latest \
          .
    - stage: docker
      name: "Building sysmoon in a Debian container"
      script:
        - |
          docker build \
          --file dockerfiles/debian.dockerfile \
          --tag sysmoon-deb:latest \
          .
    - stage: docker
      name: "Building sysmoon in a ArchLinux container"
      script:
        - |
          docker build \
          --file dockerfiles/archlinux.dockerfile \
          --tag sysmoon-arch:latest \
          .
