version: '3.3'

##
#
# Usage without Rake
#
# docker-compose build
# docker-compose up --detach
# docker attach {hash of a container}
# ...
# docker-compose rm --force
#
##

services:
  node-1:
    build:
      context: .
      dockerfile: dockerfiles/debian.dockerfile
    image: evesync-test:latest
    ports:
      - "55432" # evehand
    tty: true
    stdin_open: true
    volumes:
      - $PWD:/evesync

  node-2:
    build:
      context: .
      dockerfile: dockerfiles/debian.dockerfile
    image: evesync-test:latest
    ports:
      - "55432" # evehand
    tty: true
    stdin_open: true
    volumes:
      - $PWD:/evesync
