version: '3.3'

# docker-compose build
# docker-compose up --detach
# docker attach {hash of a container}
# ...
# docker-compose rm --force

services:
  node-1:
    build:
      context: .
      dockerfile: dockerfiles/centos.dockerfile
    image: evesync-debian:latest
    ports:
      - "55432" # evehand
    tty: true
    stdin_open: true

  node-2:
    build:
      context: .
      dockerfile: dockerfiles/centos.dockerfile
    image: evesync-debian:latest
    ports:
      - "55432" # evehand
    tty: true
    stdin_open: true
